# Generated by Django 4.1.3 on 2022-11-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='shorturl',
            field=models.CharField(max_length=15),
        ),
    ]
