# Generated by Django 4.1.3 on 2022-11-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_urlshortener_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='shorturl',
            field=models.CharField(max_length=30),
        ),
    ]
