# Generated by Django 4.1.3 on 2022-11-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapi', '0003_alter_urlshortener_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='longurl',
            field=models.URLField(max_length=225),
        ),
    ]
